services:
  cyber-guardians-api:
    container_name: cyber-guardians-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/api  
    ports:
      - "8000:8000" 
    environment:
      - DATABASE_URL=your_database_url
      - SECRET_KEY=your_secret_key
